### ISSUE TITLE
/workdir/data-processing/scripts/adapter_clipping.sh: line 38: [: =: unary operator expected

### ISSUE THREAD

**Issue by LZarri** [therkildsen-lab/genomic-data-analysis#3]
I am getting an error when attempting to do adapter_clipping. See the title for the error, and I get this repeating many times over with alternating "line 38" and "line 35". As per this link (https://stackoverflow.com/questions/13617843/unary-operator-expected-error-in-bash-if-condition) perhaps the brackets on lines 35 and 38 need double-brackets?

Code to run adapter_clip is below. All data is in /workdir/smallmouth

nohup bash /workdir/data-processing/scripts/adapter_clipping.sh \
'/workdir/smallmouth/sample_lists/sample_list_lane_2_nextera.txt' \
'/workdir/smallmouth/sample_lists/sample_table_lane_2.tsv' \
/workdir/smallmouth/demultiplexed/ \
/workdir/smallmouth/ \
_R1.fastq.gz \
_R2.fastq.gz \
/workdir/cod/reference_seqs/NexteraPE_NT.fa >& \
'/workdir/smallmouth/nohups/adapter_clipping_lane_2_nextera.nohup' &

**Comment by nicolas931010** [comment]
I did some digging, and found that both your sample list and sample table have CRLF line terminators, which is [the line ending that Windows uses but isn't quite compatible with Unix](https://www.networkworld.com/article/3107972/windows-vs-unix-those-pesky-line-terminators.html). Did you use Excel or word to edit these files? And would you mind trying to convert these files to Unix format and try again?

**Comment by LZarri** [comment]
Nicholas you nailed it! The link above works. Solution:

in ~/sample_lists, check whether any lines have CRLF
`file * | grep CRLF`

If they do, get rid of those pesky line-terminators
`dos2unix sample_list_lane_2.txt`

**Comment by nicolas931010** [comment]
Great. I'll close this issue then and will update the README with a link to this issue.
